Develop/step1
Ivanov-DM/react-burger pull request #1
Opened 2023-03-29 22:33 UTC by Ivanov-DM

Вёрстка первого экрана проекта. Добавлены компоненты AppHeader, BurgerIngredients и BurgerConstructor.

2023-03-30 03:51 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно исправит ошибки в консоли: <https://disk.yandex.com/i/EmdLpkD-c0tjzw>;

- Переименуйте файлы компонентов (имя файла, должно соответствовать имени папки), например: `App.js` в `app.js`, `AppHeader.js` в `app-header.js`; чтобы везде был единый стиль нейминга. <https://noteskeeper.ru/heritage/672/> - чтобы после изменения имени файлов, всё осталось нормально;

- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

  Проверьте во всём проекте.

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-03-30 03:51 UTC, ArslanDev666 commented on src/components/burger-ingredients/BurgerIngredients.js
> +            <div style={{display: 'flex'}}>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-03-30 03:51 UTC, ArslanDev666 commented on src/components/burger-constructor/BurgerConstructor.js
> +});
**Надо исправить:**

Во многих компонентах будет дублироваться описание PropTypes ингредиента.
Следует вынести его в отдельный файл (можно создать файл `prop-types.js` в папке `utils`) и переиспользовать описание пропсов ингредиента, а не дублировать;

2023-03-30 03:51 UTC, ArslanDev666 commented on src/components/burger-constructor/BurgerConstructor.js
> +    const ingredientsSet = props.ingredientSet;
**Можно лучше:**

Лучше заранее сделать фильтрацию от булок, а не делать это в рендере.

```js
const ingredients = props.ingredientSet.filter(ingredient => ingredient.type !== 'bun');
```

2023-03-30 03:51 UTC, ArslanDev666 commented on src/components/burger-constructor/BurgerConstructor.js
> +    }
**Можно лучше:**

Думаю тут нет необходимости в этому, лучше сразу писать `ConstructorElement` в рендере.

2023-03-30 03:51 UTC, ArslanDev666 commented on src/components/burger-constructor/BurgerConstructor.js
> +                text={bunData.name}
**Надо исправить:**

По макету у булок должна быть приписка `(верх)` и `(низ)`.

2023-03-30 03:51 UTC, ArslanDev666 commented on src/components/burger-constructor/BurgerConstructor.js
> +
**Можно лучше:**

аналогичное замечание с `renderBuns`.

Лучше сразу всё писать в рендере, а не делать новые функции для этого;

2023-03-30 03:51 UTC, ArslanDev666 commented on src/components/burger-constructor/BurgerConstructor.js
> +    ingredientSet: PropTypes.arrayOf(ingredientProptypes.isRequired)
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2023-03-30 03:51 UTC, ArslanDev666 commented on src/components/burger-ingredients/BurgerIngredients.js
> +                                        </li>
**Можно лучше:**

Для ингредиента лучше создать отдельный компонент, например `burger-ingredient` и переиспользовать.

2023-03-30 03:51 UTC, ArslanDev666 commented on src/components/burger-ingredients/BurgerIngredients.js
> +                    </ul>
**Можно лучше**

у каждой категории ингредиентов дублируется верстка, лучше вынести отдельный компонент `ingredients-category` и переиспользовать его

2023-03-30 03:51 UTC, ArslanDev666 commented on src/components/burger-ingredients/BurgerIngredients.js
> +                                if (ingredient.type === 'bun') {
**Можно лучше**

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив.

Например:

```js
const buns = data.filter((item) => item.type === 'bun'), [data];
const mains = data.filter((item) => item.type === 'main'), [data];
const sauces = data.filter((item) => item.type === 'sauce'), [data];

return (
   ....................
   {buns.map(....................)}
   ..................
)
```

А не располагать фильтрацию в самом jsx

2023-03-30 03:51 UTC, ArslanDev666 commented on src/components/burger-ingredients/BurgerIngredients.js
> +    ingredients: PropTypes.arrayOf(ingredientProptypes.isRequired)
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2023-03-30 19:42 UTC, Ivanov-DM commented on src/components/burger-ingredients/BurgerIngredients.js
> +            <div style={{display: 'flex'}}>
Вынес стили в класс tabs в файле burgerIngredientsStyle

2023-03-30 19:45 UTC, Ivanov-DM commented on src/components/burger-constructor/BurgerConstructor.js
> +});
Вынес PropTypes ингредиента в файл prop-types.js в папке utils

2023-03-30 19:49 UTC, Ivanov-DM commented on src/components/burger-constructor/BurgerConstructor.js
> +    ingredientSet: PropTypes.arrayOf(ingredientProptypes.isRequired)
Добавил

2023-03-30 19:49 UTC, Ivanov-DM commented on src/components/burger-ingredients/BurgerIngredients.js
> +    ingredients: PropTypes.arrayOf(ingredientProptypes.isRequired)
Добавил

2023-03-30 19:52 UTC, Ivanov-DM commented on src/components/burger-constructor/BurgerConstructor.js
> +    const ingredientsSet = props.ingredientSet;
Отфильтровал все, что не bun в константу sauceAndMain

2023-03-30 19:58 UTC, Ivanov-DM commented on src/components/burger-constructor/BurgerConstructor.js
> +    }
Удалил функцию renderBuns и перенес ConstructorElement в render

2023-03-30 19:59 UTC, Ivanov-DM commented on src/components/burger-constructor/BurgerConstructor.js
> +                text={bunData.name}
Удалил функцию renderBuns и перенес ConstructorElement в render

2023-03-30 20:01 UTC, Ivanov-DM commented on src/components/burger-constructor/BurgerConstructor.js
> +
Удалил функцию renderIngredient и перенес ConstructorElement в render

2023-03-30 20:36 UTC, Ivanov-DM commented on src/components/burger-ingredients/BurgerIngredients.js
> +                                        </li>
Добавил компонент BurgerIngredient c соответствующим модулем стилей

2023-03-30 20:40 UTC, Ivanov-DM commented on src/components/burger-ingredients/BurgerIngredients.js
> +                                if (ingredient.type === 'bun') {
Вынес соответствующие наборы ингредиентов в константы buns, mains, sauces

2023-03-30 20:53 UTC, Ivanov-DM commented on src/components/burger-ingredients/BurgerIngredients.js
> +                    </ul>
Добавил компонент IngredientsCategory c соответствующим модулем стилей

2023-03-31 05:16 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличая работа.

### **Вы молодец! Приступайте к выполнению следующего этапа, не пугайтесь, работа не принята, чтобы была возможность отправить на проверку следующий этап.**

- Все замечания были исправлены;

### **Нужно исправить:**

- Нужно исправить ошибку при запуске приложения (чтобы воспроизвести склоньте свой проект): <https://disk.yandex.com/i/mfRwQXI5k5D94w>, <https://disk.yandex.com/i/tNNg4k3WgM6uxg>;

2023-03-31 05:16 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.js
> +import {ingredientProptypes} from "../../utils/prop-types";
**Надо исправить:**

кажется, файла в репозитории нету...

2023-04-03 22:23 UTC, merged