add components Modal, ModalOverlay, IngredientDetails and OrderDetails
Ivanov-DM/react-burger pull request #2
Opened 2023-04-07 12:31 UTC by Ivanov-DM

Реализовано подключение к API, для запроса исходных данный, реализованы компоненты Modal, ModalOverlay, IngredientDetails and OrderDetails

2023-04-07 15:16 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Есть модальные окна;
- Данные получают с сервера;

### **Отметил мелкие замечания в коде, которые нужно исправить. Работа супер 🔥**

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь <https://learn.javascript.ru/coding-style>. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (<https://prettier.io/>)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-04-07 15:16 UTC, ArslanMustafin commented on src/components/app/app.js
> +    const [modalIngredient, setModalIngredient] = React.useState({});
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-04-07 15:16 UTC, ArslanDev666 commented on src/components/app/app.js
> +const API_URL = 'https://norma.nomoreparties.space/api/ingredients';
**Надо исправить:**

Вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` в константу, в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2023-04-07 15:16 UTC, ArslanDev666 commented on src/components/app/app.js
> +                    ...ingredients.data
**Можно лучше:**

тут лучше использовать функциональное обновление. https://ru.reactjs.org/docs/hooks-reference.html#functional-updates

2023-04-07 15:16 UTC, ArslanDev666 commented on src/components/app/app.js
> +            }).catch(err => console.log(err));
**Можно лучше:**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}
```

и разместить их в отдельном файле `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-04-07 15:16 UTC, ArslanDev666 commented on src/components/app/app.js
>              </div>
**Рекомендую исправить:**

Лучше разместить попапы в компонентах `burger-ingredients` и `burger-constructor`, т.к. в `app`, модальные окна при открытии/закрытии, будут вызывать перерендер всего приложения; А также лучше писать `jsx` код тут, а не делать переменные, немного хуже читаемость кода становится, приходится возвращаться к переменным и смотреть что это.

2023-04-07 15:16 UTC, ArslanDev666 commented on src/components/modal/modal.js
> +            </ModalOverlay>
**Можно лучше:**

Тут можно проще написать, без вложенности в `ModalOverlay`;

```js
<>
  <ModalOverlay onClose={...} />
  <div className={styles.modal}></div>
</>
```

попробуйте данную структуру, тогда не будет нужно останавливать всплытие.

2023-04-07 15:16 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.js
> +                    onClick={() => props.setVisible(true)}
**Можно лучше:**

Лучше вынести обработчик событий в отдельную функцию.

2023-04-07 20:04 UTC, Ivanov-DM commented on src/components/app/app.js
> +    const [modalIngredient, setModalIngredient] = React.useState({});
Исправил

2023-04-07 20:13 UTC, Ivanov-DM commented on src/components/app/app.js
> +const API_URL = 'https://norma.nomoreparties.space/api/ingredients';
Исправил, вынес базовый адрес сервера в utils/constants.js

2023-04-08 11:16 UTC, Ivanov-DM commented on src/components/app/app.js
> +            }).catch(err => console.log(err));
Вынес запрос в файл utils/burger-api.js

2023-04-08 11:43 UTC, Ivanov-DM commented on src/components/app/app.js
>              </div>
Перенес попапы в соответствующие компоненты, jsx код убрал из переменной

2023-04-08 11:55 UTC, Ivanov-DM commented on src/components/modal/modal.js
> +            </ModalOverlay>
Убрал вложенность в ModalOverlay

2023-04-08 12:24 UTC, Ivanov-DM commented on src/components/burger-constructor/burger-constructor.js
> +                    onClick={() => props.setVisible(true)}
Вынес обработчик в функцию

2023-04-08 12:25 UTC, Ivanov-DM commented on src/components/app/app.js
> +                    ...ingredients.data
Добавил обновление state с помощью функции

2023-04-09 07:23 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-04-11 20:14 UTC, merged