add redux and react-dnd in project
Ivanov-DM/react-burger pull request #4
Opened 2023-05-04 13:14 UTC by Ivanov-DM

Добавлена реализация второй части проектной работы 8-го месяца.

2023-05-04 14:46 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая организация хранилища
- Редьюсеры - чистые функции

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- для атрибута key в конструкторе нужно использовать для ингредиента уникальный uuid (Вам нужно его генерировать во время сброса в зону DnD). Это можно делать с помощью библиотеки uuid https://www.npmjs.com/package/uuid , или Вам должны были показать, как это сделать, иначе некорректно может работать DND. А в key будет уже просто key={ item.uuid }
- Не у всех компонентов указан `propTypes`
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

Более подробно описание проблемы смотрите комментарии в pull request.

**Можно лучше**
- желательно очищать конструктор после успешного получения номера заказа с сервера в блоке then, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-04 14:46 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +  const { burgerIngredients, orderDetails, totalPrice } = useSelector(
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-05-04 14:46 UTC, andryxxa93 commented on src/components/sorted-element/sorted-element.js
> +const SortedElement = ({ children, index }) => {
**Надо исправить**

для этого компонента так же нужно описать PropTypes

2023-05-04 21:38 UTC, Ivanov-DM commented on src/components/sorted-element/sorted-element.js
> +const SortedElement = ({ children, index }) => {
Добавил propTypes для компонента SortedElement

2023-05-05 19:22 UTC, Ivanov-DM commented on src/components/burger-constructor/burger-constructor.js
> +  const { burgerIngredients, orderDetails, totalPrice } = useSelector(
Добавил именованную функцию для передачи в useSelector в тех компонентах, где вызывается хук useSelector,

2023-05-06 09:54 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-10 20:34 UTC, merged